services:
  db:
    image: postgres:17.2-alpine3.21
    restart: always
    # postgres needs more shared memory, MOAR
    shm_size: 128mb
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8080:8080

volumes:
  database:
