# Generated by Django 5.1.4 on 2025-01-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('experience', models.PositiveIntegerField()),
                ('breed', models.CharField(max_length=50)),
                ('salary', models.PositiveIntegerField()),
            ],
        ),
    ]
